server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: guli-vod # 服务名

  #inputstream上传的时候需要配置，javascript sdk不需要
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认10M

aliyun:
  vod:
    file:
      keyid: LTAI4FjoE4WHevyWVKYZ8MHK
      keysecret: v8T0Upqf0FgqAzSYdhsmdgXO4clKkO
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9110/eureka/
  instance:
    prefer-ip-address: true
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    # 配置说明
    # lease-renewal-interval-in-seconds 每间隔5s，向服务端发送一次心跳，证明自己依然”存活“，默认 30
    lease-renewal-interval-in-seconds: 5
    # lease-expiration-duration-in-seconds  告诉服务端，如果我10s之内没有给你发心跳，就代表我“死”了，将我踢出掉，默认 90
    lease-expiration-duration-in-seconds: 10