server:
  port: 8160 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: guli-sms # 服务名
  redis:
    host: 192.168.191.128
    port: 6379
    database: 0
    timeout: 1800000
   # password: redis密码
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9110/eureka/
  instance:
    prefer-ip-address: true
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    # 配置说明
    # lease-renewal-interval-in-seconds 每间隔5s，向服务端发送一次心跳，证明自己依然”存活“，默认 30
    lease-renewal-interval-in-seconds: 5
    # lease-expiration-duration-in-seconds  告诉服务端，如果我10s之内没有给你发心跳，就代表我“死”了，将我踢出掉，默认 90
    lease-expiration-duration-in-seconds: 10

#阿里云短信(这是老师开通的信息)以前的是调用第三方的接口
aliyun:
  sms:
    regionid: cn-hangzhou
    keyid: LTAI4FjoE4WHevyWVKYZ8MHK
    keysecret: v8T0Upqf0FgqAzSYdhsmdgXO4clKkO
    templatecode: SMS_96695065
    signname: 谷粒
